### ISSUE TITLE
Min hugo version

### ISSUE THREAD

**Issue by limonmecanico** [Fastbyte01/KeepIt#1]
I added your theme to my hugo site on Netlify (created via netlifycms just today). When trying to deploy I keep getting this error:
`ERROR 2019/03/08 22:54:41 Current theme does not support Hugo version 0.46. Minimum version required is 0.53`
It works fine with other themes, but yours is spectacular.
Any help would be much appreciated.

**Comment by Fastbyte01** [comment]
Hi @limonmecanico I have created and tested the theme with the version 0.53 of hugo. You can try to use the version 0.46 that you are using to deploy to Netlify simply by changing the Hugo version on the Netlify.toml. Let me now if this work and please can you share the link to your site with me so I can insert it on the readme file.

**Comment by limonmecanico** [comment]
Hi!
I did a little research and it seems to be a problem with the netlifycms 1-button install. It creates the site using Victor Hugo and not Hugo itself, so changing the theme (to any theme, not just yours) becomes a nightmare.
I deleted the site and I'll try to install a new one using the convencional hugo method. I'll share the link when it's done. 
Thanks!
