### ISSUE TITLE
i18n for english is missing

### ISSUE THREAD

**Issue by cnf** [Fastbyte01/KeepIt#10]
i18n for english seems to be missing. when having the default language set to english, all i18n strings are blank.

This can also be seen on the demo page: https://themes.gohugo.io//theme/KeepIt/post/emoji-support/

**Comment by Fastbyte01** [comment]
Hi @cnf, Thanks for the feedback. The bug is fixed with the commit 565202fd134562bfa3da8387e5cc3682ff9939dc and the demo have been updated.

**Comment by cnf** [comment]
Thanks! https://github.com/Fastbyte01/KeepIt/commit/565202fd134562bfa3da8387e5cc3682ff9939dc fixed it for me, but the demo site doesn't seem updated, FYI.

**Comment by Fastbyte01** [comment]
@cnf thanks for your feedback. That's true the demo on the Hugo site themes need to be updated. Now I write to developers of the site and ask to update the demo.
