### ISSUE TITLE
Not all social icons work on mobile.

### ISSUE THREAD

**Issue by cnf** [Fastbyte01/KeepIt#12]
On iOS, not all social icons show up.

It seems LinkedIn. Twitter, Facebook, Pinterest, and Reddit don't work.

![rqjpona](https://user-images.githubusercontent.com/252949/54448314-b5d0f380-474b-11e9-8a68-5832143c6995.jpg)

**Comment by Fastbyte01** [comment]
@cnf Thanks for the feedback, the demo on the hugo theme site needs to be updated. Can you please test if all is working good with the demo site that it's linked on the Readme? This [one](https://suspicious-archimedes-ab369d.netlify.com/). Thanks again for your feedback and if you are using KeepIt please share the link to your site (If you want :)) as I can insert it in the readme.

**Comment by cnf** [comment]
No, it doesn't seem to.
![IMG_2148](https://user-images.githubusercontent.com/252949/54464240-1f65f780-4776-11e9-97c1-2afb73b5aeee.jpeg)

I am still evaluating hugo / your theme atm... I'll see once I have made a decision :P

**Comment by Fastbyte01** [comment]
That's is a really strange behaviour as I have tested the web site with webkit, that is the rendering engine of Safari and the sites works flawless. Can be a cache problem? Can you try with another browser?

**Comment by cnf** [comment]
Ah, culprit found. adblockers / content blockers were blocking certain sites. Are the icons downloaded remotely?

**Comment by Fastbyte01** [comment]
No the icons are stored locally. Now you have solved the problem? The icons are showing normally?

**Comment by cnf** [comment]
They work when I disable my content blockers, they stop working when I turn them on.

Not sure why, especially as the link is still there, it is just the icon that turns invisible.

**Comment by Fastbyte01** [comment]
Ok, thanks again for your feedback.
