### ISSUE TITLE
Roboto font not loaded

### ISSUE THREAD

**Issue by SilkeHenderickx** [Fastbyte01/KeepIt#14]
Initially I saw that apostrophe's always had 2 spaces behind them. 

![image](https://user-images.githubusercontent.com/28140438/54494013-2c016180-48d6-11e9-9dfe-d7b88c950b3e.png)

This was due to font "Microsoft Yahei" being loaded in instead of "Roboto", due to a spelling error.

In: KeepIt/assets/css/_common/_core/base.scss
change line 34: "Roborto" to "Roboto"

This fixes the apostrophe issue. However, it's loading in Josefin sans now, instead of Roboto, and I cannot find why. Josefin is fine as a font tho, so not necessarily an issue anymore.

![image](https://user-images.githubusercontent.com/28140438/54494161-b5fdfa00-48d7-11e9-8c63-deb68c3ca551.png)

This file is the only place where "josefin sans" is present:
KeepIt/resources/_gen/assets/scss/css/main.scss_b95b077eb505d5c0aff8055eaced30ad.content

If you have time, could you update the base.scss file to remove the apostrophe error? Thank you!

**Comment by Fastbyte01** [comment]
Hi @SilkeHenderickx, bug fixed with the commit 94ed00ab04b29264e2b08b4e0cdd7afc9891bc12.
