### ISSUE TITLE
Possibility to add other social media sites?

### ISSUE THREAD

**Issue by cnf** [Fastbyte01/KeepIt#15]
Would it be possible to add things like thingiverse, mastodon, matrix/riot etc?

Or a method to add your own social icons without having to copy (and thus override) the partials/social.html file?

Thanks

**Comment by Antguz** [comment]
Hi, 

I already love this hugo theme and I was wondering the same. Do you think that it is possible to you to add other social media such as google-scholar or ResearchGate?

Thanks in advance!

**Comment by Fastbyte01** [comment]
Hi @Antguz, Now with the commit b925b96ef98cbf35e3283e820ed26d3ce5ef3b2f KeepIt support have social links to both Google scholar and Research Gate.

**Comment by Fastbyte01** [comment]
Hi @cnf the only way to add more social links is to add this to the `partial/social.html`. As I know there are no other easy way to let user insert they social links. KeepIt have over 50 different social links, you can see the complete list [here](https://github.com/Fastbyte01/KeepIt/wiki/List-of-social-platforms-supported-out-of-box). If you want can share a list of other social links that you need and I can do my best to add it to KeepIt.

**Comment by cnf** [comment]
Thanks for adding Mastodon. Mastodon is a federated system though, so there are 100ds of instances, not just mastodon.social. The link is always https://{{instance_name}}/@{{username}} though.

Is the list of social platforms you can integrate dependent on if iconfont has an icon for it, btw?

I'd like things like [thingiverse](https://www.thingiverse.com/cnfer/about) and [myminifactory](https://www.myminifactory.com/) if that is possible.

Also, could you not add a {{partial social_custom.html}}, and have that as an empty file, so people can override just that to append to it, without having to override it? I prefer to not override not too many of the theme files, as that means I won't get updates to the theme...

Thanks for your help!

**Comment by Fastbyte01** [comment]
@cnf  a `social_custom.html` file is necessary because hugo have already a way that let you customize the theme in a simple way without touching the original code of the theme. For esempale if you want to create your version of `/themes/KeepIt/layouts/partial/social.html` you only need to create `/layouts/partial/social.html` in this way you don't need to touch the theme. For more info how this work you can see the Hugo documentation [here](https://gohugobrasil.netlify.com/themes/customizing/).

**Comment by Fastbyte01** [comment]
@cnf for the icons I use the icons that are on iconfont and the social links that I insert depend on it but if there are much request about a social that dosn't have the icon on iconfont I can try to create it. I for now implemented all the most know social platform.

**Comment by Fastbyte01** [comment]
@cnf for Mastodon yes I know it as the istances, but I believe that is more simple to change the URL in `social.html`, for this I have inserted only mastodon.social.

**Comment by cnf** [comment]
@Fastbyte01 right, but if I overrule `layouts/partial/social.html`, and you later update it, I have to manually merge those changes. Trying to find a way to have it customizable, and have your updates be applied automatically as well.

**Comment by Fastbyte01** [comment]
@cnf you don't necessarily need to update it if you choose to use only some social links, the theme now have over 50 social links but probably people use no more than 10. I for example use only 4. In this way you can continue to update the theme with all the new feature that being added but can keep your list of social links.

**Comment by Antguz** [comment]
@Fastbyte01 it seems that Researchgate works, but not google scholar. The params.social is google-scholar and what we need to add is the user id, right?

**Comment by xxxserxxx** [comment]
> @cnf for the icons I use the icons that are on iconfont and the social links that I insert depend on it but if there are much request about a social that dosn't have the icon on iconfont I can try to create it. I for now implemented all the most know social platform.

Adding the social links in `social.html` is pretty easy; I got stuck with the fonts. How are you adding icons to the font files? Do you have a script?

I'd like to request adding glyphs for:

- [Sourcehut](https://sr.ht), a fairly popular alternative to Github / Gitlab / Bitbucket. Their icon is just a circle, ◌
- [Matrix](https://matrix.org/), the IM/chat room system. Their icon is `[m]`.
- [Simplex](https://simplex.chat/), who's logo is a sort of rotated `#`
- [Jabber](http://www.jabber.org/), maybe? Lots of people still using that. I don't know if there's an official logo for the protocol; Jabber.org's logo is a lightbulb.
