### ISSUE TITLE
Adding avatar

### ISSUE THREAD

**Issue by Antguz** [Fastbyte01/KeepIt#16]
I was trying to change my avatar I found that with your new commit (b925b96) that is not possible. Specifically, the avatar could be changed before changing the path below [params] > avatar =, but now that is not possible. I tried to use the exampleSite but without success. Likewise, the exampleSite demo does not load the default avatar. What I can do?

**Comment by Fastbyte01** [comment]
Hi @Antguz , The avatar now use the [gravatar](https://gravatar.com/) system. To use it you need to create an account on the gravatar site and upload your immage. In the KeepIt theme, you need to insert the email address that you used to register your account and the theme automatically load the avatar. In the next days I add again the support for the local avatar together with the gravatar, for people that dosn't want or dosn't can use the gravatar system.

**Comment by Fastbyte01** [comment]
@Antguz  now with this commit 2fa50697fdf84abec1f8c05f0a49616e98d228d1 you can use the local avatar if you want to use the gravatar.
