### ISSUE TITLE
Feature request: Weibo social media support

### ISSUE THREAD

**Issue by zwpaper** [Fastbyte01/KeepIt#2]
Hi, thanks for the great theme

When I was using it, I want to add a social media `Weibo`, this is a pop social media in Chine.

I tried adding it myself, but `iconfont` stopped me.

Can u help?

BTW, the URL should be: weibo.com/username

**Comment by Fastbyte01** [comment]
@zwpaper your request will be available soon.

**Comment by Fastbyte01** [comment]
@zwpaper Weibo added with the commit 2640d00f5c9db540121993d28b273cde1a3c6320.
If you are using KeepIt, please share your web site link as I can add it in the readme file.

**Comment by zwpaper** [comment]
My site: https://page.codespaper.com

It's a site in Chinese.

**Comment by Fastbyte01** [comment]
@zwpaper thanks for sharing your blog will be added soon to readme.
