### ISSUE TITLE
blockquote in dark theme mode

### ISSUE THREAD

**Issue by isnanx** [Fastbyte01/KeepIt#21]
Hi, thanks for your theme, it's nice, however, I found it that when writing the blockquote in dark theme mode, the style is not the same, please take a look if you have time, thanks.

**Comment by isnanx** [comment]
![image](https://user-images.githubusercontent.com/49234985/56675550-f3cc1a80-66ee-11e9-998f-50fe878ce14c.png)

**Comment by Fastbyte01** [comment]
Fixed with the commit 764d4adaf7131160c1aff576c25ac98186944ef2

**Comment by isnanx** [comment]
Ok, thanks. @Fastbyte01
