### ISSUE TITLE
Home post model not work

### ISSUE THREAD

**Issue by isnanx** [Fastbyte01/KeepIt#22]
Hi, an error occurs when generating pages, take a look when it's convenient please, thanks.
![ki](https://user-images.githubusercontent.com/49234985/56845008-ef6d5080-68ec-11e9-8b6d-b7ed12376797.png)

**Comment by Fastbyte01** [comment]
Fixed with the commit 8b49c5eaa2d68eeaf0549df00020c1191d1c37b1
