### ISSUE TITLE
Hugo 0.55.4 build warning, Page's .URL and Page's .RSSLink are deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by isnanx** [Fastbyte01/KeepIt#25]
Hi, sorry to bother you all the time, I tried to modify the page as explained in the warning when generating pages, but errors occur, any advice, please.
![image](https://user-images.githubusercontent.com/49234985/56965388-c3bdc500-6b8f-11e9-91e1-eb4e6090ab51.png)

**Comment by ivlioioilvi** [comment]
I also just want to feedback this mistake.
The Hugo_0.55.3 I used

**Comment by Fastbyte01** [comment]
Fixed the various warning with the commit fc248e808b1de1d4a5fc3219bfee4ef303721f6f

**Comment by isnanx** [comment]
Thanks @Fastbyte01, it's working well now.  :)
