### ISSUE TITLE
Make primary avatar link customizable (not just hard-coded as /posts)

### ISSUE THREAD

**Issue by tlianza** [Fastbyte01/KeepIt#27]
The url `/posts` is hardcoded here and a few other spots:
https://github.com/Fastbyte01/KeepIt/blob/3e2972c318b3c8297a5ac775cb897adefa90b2ee/layouts/partials/home_profile.html#L6

I don't personally use hugo for a blog, and have no content type named 'posts', so it'd be nice if this were a configuration option.

**Comment by Fastbyte01** [comment]
Hi @tlianza Can be a good idea but KeepIt is developed as a blog theme, and for now I don't have idea about changing the primary use of it. For now have to flag your idea as won't fix.
