### ISSUE TITLE
dark-theme as default?

### ISSUE THREAD

**Issue by htothek** [Fastbyte01/KeepIt#28]
Hello -- Great theme by the way, I love it!  

Is it possibly to make the initial theme the "dark-theme"?  I've tried to edit the baseof.html and set <body class="dark-theme"> but it doesn't seem to stick.

Any help would be appreciated.  Thank you again for all your hard work!

**Comment by mitchellurgero** [comment]
The work around I use for this is:

In `themes/keepit/assets/js/main.js`: (Line 32 -33, add under the line that says `_Blog.toggleTheme = function() {` )

```js
if(!window.localStorage.getItem('theme')){
	window.localStorage.setItem('theme', 'dark');
}
```
