### ISSUE TITLE
[Error] Cannot create new post by hugo

### ISSUE THREAD

**Issue by srdg** [Fastbyte01/KeepIt#30]
Running the command   
`hugo new projects/projectsample.md` gives the following error:  
`Error: yaml: line 1: did not find expected key`  
I have to create every single file with the front-matter manually.
Can anyone tell me the possible causes and solutions?

**Comment by Fastbyte01** [comment]
Hi @srdg I have tested your command with the KeepIt theme on my Hugo install and dosn't have that error.
