### ISSUE TITLE
[Error] Error building site

### ISSUE THREAD

**Issue by Cool-Pan** [Fastbyte01/KeepIt#31]
Use the new version of hugo to building, prompting the following error.

```Text
Total in 124 ms
Error: Error building site: failed to render pages: render of "taxonomy" failed: "/My-Blog/themes/KeepIt/layouts/_default/list.html:5:14": execute of template failed: template: _default/list.html:5:14: executing "content" at <.Paginate>: error calling Paginate: cannot convert type page.PagesGroup to Pages
```

Hugo version: ``Hugo Static Site Generator v0.57.2/extended linux/amd64 BuildDate: unknown``

Another, did the author give up the project?

**Comment by Fastbyte01** [comment]
Hi @Cool-Pan I'm using the theme with latest version of hugo and dosn't have errors
