### ISSUE TITLE
Show posts on homepage don't work

### ISSUE THREAD

**Issue by SuLingGG** [Fastbyte01/KeepIt#39]
It's a fantastic theme on Hugo~

But when I use 

```
[params]
 home_mode = "post"
```

To show posts on homepage, it doesn't work, the homepage only output "Posts" link and the time of the latest post:

![Snipaste_2019-10-25_22-16-03](https://user-images.githubusercontent.com/22287562/67578684-8e2c1a00-f775-11e9-9e24-a1d47097fc6b.png)

My hugo version is ` v0.58.3-4AAC02D4 windows/amd64`. Tested on Linux have the same problem.

**Comment by Fastbyte01** [comment]
Fixed with commit dd68036161f771a2a7091ed21486aca0ace7114a.
Now tested against the last release of hugo 0.59.1.
