### ISSUE TITLE
How to use lightGallery?

### ISSUE THREAD

**Issue by UnicodeAlt255** [Fastbyte01/KeepIt#4]
Sorry for the newbie question, but when I add images to a page, it doesn't seem to take advantage of lightGallery at all. I am simply adding images to a markdown file, is there something I'm missing?

**Comment by Fastbyte01** [comment]
Hi @UnicodeAlt255, you have to simply add the image with the markdown syntax:

```
![imagename](yourimagelink)

```

**Comment by Fastbyte01** [comment]
@UnicodeAlt255 If you are using KeepIt as your theme please share the link to your site so I can add it in the readme file.
