### ISSUE TITLE
Documentation Request:  Image gallery example using lightgallery in included examplesite

### ISSUE THREAD

**Issue by gitclue** [Fastbyte01/KeepIt#40]
I am unsure how to use lightgallery to display images in form of gallery.  An example image gallery in your  KeepIt theme examplesite included with the theme would do wonders.

Please add an example gallery to the KeepIt theme example site.

Thank you!

-----------------------

Non sono sicuro di come utilizzare LightGallery per visualizzare le immagini in forma di galleria. Una galleria di immagini di esempio nel tuo esempio di tema KeepIt inclusa nel tema farebbe meraviglie.

Aggiungi una galleria di esempio al sito di esempio del tema KeepIt.

Grazie!

-------------------------

Je ne sais pas comment utiliser lightgallery pour afficher des images sous forme de galerie. Un exemple de galerie d’images dans votre exemple de thème KeepIt inclus dans le thème ferait des merveilles.

Veuillez ajouter un exemple de galerie au site exemple de thème KeepIt.

Je vous remercie!

**Comment by Fastbyte01** [comment]
Hi @gitclue You can find how to use lightgallery [here](https://github.com/sachinchoolur/lightGallery).

**Comment by sycured** [comment]
Hi @Fastbyte01 ,
Can you add an example using markdown can be good because I'm not fan to integrate hardcoded html in markdown's file.
Thanks

**Comment by Fastbyte01** [comment]
Hi, 
thanks for you feedback.

It’s a good idea, when I have some spare time I update the wiki with the info about using lightgallery with the theme.
