### ISSUE TITLE
Add Categories labels will lead to build failed

### ISSUE THREAD

**Issue by BlankerL** [Fastbyte01/KeepIt#41]
![image](https://user-images.githubusercontent.com/24969376/68547904-43bbc600-0422-11ea-8f04-f17dda7761fb.png)
Here is the issue, when I tried to add Categories in my post, there will be an issue saying **failed to unmarshal YAML: yaml: line 5: did not find expected key**, is anyone else has the same issue?

OS: macOS Catalina
Hugo: Hugo Static Site Generator v0.59.1/extended darwin/amd64

**Comment by Fastbyte01** [comment]
YAML is case sensitive.
Categories isn't the same as categories.
And if for you is more convenient you can write categories in this way:
```
categories: 
  - Open Source

```

**Comment by BlankerL** [comment]
Thank you so much for your help! I am a newbee to Hugo, and I am not very sure whether I need to have another YAML to store my categories or not?
Simply switch to lower case still does not work.
![image](https://user-images.githubusercontent.com/24969376/68563063-5b796580-0487-11ea-920f-7332f31cb879.png)

**Comment by BlankerL** [comment]
I tried to replace the original file header with the file headers in your example, and everthing works. 
![image](https://user-images.githubusercontent.com/24969376/68563617-135b4280-0489-11ea-98dd-0c53151635fe.png)
![image](https://user-images.githubusercontent.com/24969376/68563621-17876000-0489-11ea-982b-c683fe2e5875.png)
But I have no idea for the reason, and the default template will not generate a file header like yours.

**Comment by BlankerL** [comment]
Alright... I figured out the reason...
```
---
title: "Title"
date: 2019-11-11T00:19:01+08:00
draft: false
description:
categories:
 - Codings
featured_image:
author: "Author"
---
```
We should put the categories in this way, I suppose the dash is just for separating the above and below...

**Comment by Fastbyte01** [comment]
Ok, now seems that your problem is solved. I'm closing this issue.
