### ISSUE TITLE
fix the regex for img

### ISSUE THREAD

**Issue by batkiz** [Fastbyte01/KeepIt#43]
Today I noticed that *lightgallery* does not take effect in my blog, then I tried to find what's wrong with that.

After my test, I found the reason is that hugo renders img tags as `<img src="" alt="">` but not `<img src="" alt="" />` now. So the regex at [/layouts/_default/single.html#L41](https://github.com/Fastbyte01/KeepIt/blob/master/layouts/_default/single.html#L41) can't work properly.

I fixed this in my [fork](https://github.com/batkiz/left/commit/843b071382ee1b0606873dd4deaaeb628a1022f0), now the lightgallery works good.

Hope the above will help with this theme.

---

tested on `Hugo Static Site Generator v0.61.0/extended windows/amd64`, but I think this happens for all version since `Hugo v0.60.0`

**Comment by Fastbyte01** [comment]
@batkiz Thanks if you want can create a pull request and I can integrate your code in KeepIT

**Comment by telami** [comment]
good job
