### ISSUE TITLE
Highlighting customization

### ISSUE THREAD

**Issue by JoshuaMart** [Fastbyte01/KeepIt#46]
Hi,
In the readme you specify that it is possible to change the style of the "highlightng", but how?

I find that the source code integration is not very readable, mainly because when you select code, the selectione is blue/pale blue.

Thank's

**Comment by Fastbyte01** [comment]
Hi @JoshuaMart You can find the way to change the code highlighting in the google code prettify [here](https://github.com/google/code-prettify)

**Comment by JoshuaMart** [comment]
Thank's
