### ISSUE TITLE
Error: Error building site: failed to render pages: render of "page" failed:

### ISSUE THREAD

**Issue by smartczy** [Fastbyte01/KeepIt#49]
Failed to render pages when I was run `hugo server -D`.  Unfortunately I couldn't find the solution aflter I had searched on Google. Please help me to figure out. Thanks.

I create a Hugo wesite following the [Hugo's tutorial](https://gohugo.io/getting-started/quick-start/).  
Here is the error message.
```
➜  blog git:(master) ✗ hugo server -D
Built in 74 ms
Error: Error building site: failed to render pages: render of "page" failed: "/Users/xxx/go/src/github.com/smartczy/blog/themes/KeepIt/layouts/_default/single.html:66:57": execute of template failed: template: _default/single.html:66:57: executing "content" at <len ($.Param "share")>: error calling len: len of untyped nil
```
### My hugo version
```
Hugo Static Site Generator v0.69.2/extended darwin/amd64 BuildDate: unknown
```
### config.toml
```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "KeepIt"
```

PS. Can't reproduce this problem when I change to use another theme`archie`.

**Comment by ciscox83** [comment]
I have the same issue.

**Comment by Kepontry** [comment]
You can check out the **config.toml** to see if you are missing "**[params.share]**". I solved this problem by adding **[params.share]** in the **config.toml**. 

When building the site, the generator can't find the param **[params.share]** in your **config.toml** , so the issues comes out.

 I think we had better copy the config.toml in the exampleSite folder to the root directory of our website and modify it to avoid similar mistakes.

**Generator Version**:Hugo Static Site Generator v0.69.0
