### ISSUE TITLE
dark theme as default?

### ISSUE THREAD

**Issue by schwenkspace** [Fastbyte01/KeepIt#50]
I've tried to switch to the dark theme as default, but didn't work :/
Can you explain what must be changed in which file?

Thanks a lot :)

**Comment by nathanhubens** [comment]
https://github.com/Fastbyte01/KeepIt/issues/28#issuecomment-497855226

This was the solution for me :)

**Comment by schwenkspace** [comment]
Ah, thank  you :)
Didn't see the closed issues 8)
