### ISSUE TITLE
Unable to find copyright information location

### ISSUE THREAD

**Issue by JPUnD** [Fastbyte01/KeepIt#52]
Hi there, I know that this isn't exactly an issue with the theme, but after doing everything to find the copyright location in the bottom of the screen i've given up and decided to open an issue.

All i wanted was to make simple changes to it, however i've searched manually every file on root directory and also tried to find it in the theme directory but i still didn't find it. I found the place where it's written in '/public' but that will be overwritten as soon as i rebuild the website.

**Comment by Fastbyte01** [comment]
Hi @JPUnD you can change the copyright info from the config.toml or if you want to make other changes you can change the source file of the footer that are in partials and is called footer.html.
