### ISSUE TITLE
How to change hyperlink for the avatar at the home page?

### ISSUE THREAD

**Issue by hinojojojo** [Fastbyte01/KeepIt#54]
Is it possible to set a different hyperlink when you click over the avatar? for example, by default when you click on the avatar at the home page, it take you to the posts. I would like it to take you to another static page such as "about". I have been searching where to change that in the config.toml and the css at assets/_page/home.scss without success. 
Any orientation on this will be much appreciated.

**Comment by Fastbyte01** [comment]
Hi @hinojojojo you can change it modifying the file home_profile.html that are in the layouts/partials/.
