### ISSUE TITLE
Feature request: google analytics support

### ISSUE THREAD

**Issue by zwpaper** [Fastbyte01/KeepIt#6]
Hugo has `google analytics` support, but looks like need adding a template in theme, so I added 

```
{{ template "_internal/google_analytics_async.html" . }}
```

in `/layouts/partials/head.html`, and it works.

Maybe this can be added to KeepIt? and check if `googleAnalytics` is set before adding template

**Comment by Fastbyte01** [comment]
Hi @zwpaper, It' a my personal choice to not add Google Analytics in KeepIt.

The first reason is for privacy concern and second is for performance concern. 

Since it's easy to insert Google Analitycs everyone can choose to use it or not.
