### ISSUE TITLE
Copying text from a codeblock.

### ISSUE THREAD

**Issue by zuron7** [Fastbyte01/KeepIt#7]
It seems that it's not possible to copy text from a codeblock in the demo. Is that a bug or a feature?

**Comment by Fastbyte01** [comment]
Hi @zuron7 As for is now the copy of the code works, but you can't see the code being highlighted. I'm thinking to change the actual code highlighter to Chroma, the default used by hugo.

**Comment by Fastbyte01** [comment]
@zuron7 if you are using KeepIt as your theme please share the ink to your site so I can add it in the readme file.
