### ISSUE TITLE
<.Site.Params.DefaultPage>: can't evaluate field Site in type string

### ISSUE THREAD

**Issue by cnf** [Fastbyte01/KeepIt#73]
https://github.com/Fastbyte01/KeepIt/blame/67abc82f152d5cf055cd21755998288ea2aa539d/layouts/partials/home_profile.html#L6

While trying to update my site, and this theme, I am getting this error now:

```
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended darwin/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

Built in 288 ms
Error: error building site: render: failed to render pages: render of "home" failed: "themes/KeepIt/layouts/index.html:5:3": execute of template failed: template: index.html:5:3: executing "content" at <partial "home_profile.html" .>: error calling partial: "themes/KeepIt/layouts/partials/home_profile.html:6:25": execute of template failed: template: partials/home_profile.html:6:25: executing "partials/home_profile.html" at <.Site.Params.DefaultPage>: can't evaluate field Site in type string
```

Is this something I am doing wrong, or did I forget something?

Thanks!

edit: I think it might be related to this https://www.regisphilibert.com/blog/2018/02/hugo-the-scope-the-context-and-the-dot/

**Comment by cnf** [comment]
I added `{{ $default_page := .Site.Params.DefaultPage }}` to the top of home_profile.html and then changed .Site.Params.DefaultPage to $default_page, and the error is gone, so I think the `{{ with .Site.Params.avatar}}` changes the context and makes .Site unavailable.

**Comment by wangweihong** [comment]
I have the same problem.
