### ISSUE TITLE
bug:执行hugo server时报错 

### ISSUE THREAD

**Issue by tiantian185** [Fastbyte01/KeepIt#78]
WARN  The "tweet" shortcode will soon require two named parameters: user and id. See "D:\blog\hugo\MyBlog\content\posts\theme-documentation-built-in-shortcodes\index.en.md:151:1"
Built in 30161 ms
Error: error building site: render: failed to render pages: render of "page" failed: "D:\blog\hugo\MyBlog\themes\KeepIt\layouts\_default\baseof.html:13:12": execute of template failed: template: posts/single.html:13:12: executing "posts/single.html" at <partial "head/seo.html" .>: error calling partial: partial "head/seo.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.

**Comment by kitty-panics** [comment]
Delete the following from `D:\blog\hugo\MyBlog\content\posts\theme-documentation-built-in-shortcodes\index.en.md`.

```
The rendered output looks like this:

{{< tweet 917359331535966209 >}}
```
