### ISSUE TITLE
Changing title in tab

### ISSUE THREAD

**Issue by amolpatel** [Fastbyte01/KeepIt#8]
I've been trying to figure out how to keep the title of the page static. Whenever I navigate to a new tab, it changes to strange face. How do I remove that feature? Screenshot is below.

<img width="71" alt="Screen Shot 2019-03-10 at 8 53 33 PM" src="https://user-images.githubusercontent.com/6493663/54094360-a2521100-4376-11e9-8b71-2fa1b88874bf.png">

**Comment by Fastbyte01** [comment]
Hi @amolpatel to chnage the emoji that appear when windows is blur you need to modify the **main.js** file.
Find and change the this part of code:
```javascript
 window.onblur = function() {
            document.title = '_(:3 」∠ )_';
        }
```
To show the current title of the post remove the emojii and use **currentTitle**. 

The code then become:

``` javascript
window.onblur = function() {
            document.title = 'currentTitle';
        }
```

If you are using KeepIt for your site please share the link as I can insert it in the readme.

**Comment by Fastbyte01** [comment]
Hi @amolpatel I have changed the behaviour of the blur tab with the commit d85784c9c95cc7a155729aab5ae6eb47c59148e0. Now you can simply update the theme and the emoji is removed and you can show the current title of the page in the tab when it's blurred.
