### ISSUE TITLE
ERROR deprecated:

### ISSUE THREAD

**Issue by lrjsec** [Fastbyte01/KeepIt#85]
Getting these errors when trying to test it running hugo server -t KeepIt:

ERROR deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in Hugo 0.140.0. Use .Sites.Default instead.
WARN  Current environment is "development". The "comment system", "CDN" and "fingerprint" will be disabled.
当前运行环境是 "development". "评论系统", "CDN" 和 "fingerprint" 不会启用.
ERROR deprecated: .Site.IsMultiLingual was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Use hugo.IsMultilingual instead.
WARN  Raw HTML omitted while rendering "C:/Users/user/Documents/blog/themes/KeepIt/content/posts/basic-markdown-syntax/index.en.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
WARN  Raw HTML omitted while rendering "C:/Users/user/Documents/blog/themes/KeepIt/content/posts/emoji-support/index.en.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
WARN  Raw HTML omitted while rendering "C:/Users/user/Documents/blog/themes/KeepIt/content/posts/theme-documentation-content/index.en.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
WARN  Raw HTML omitted while rendering "C:/Users/user/Documents/blog/themes/KeepIt/content/posts/theme-documentation-basics/index.en.md"; see https://gohugo.io/getting-started/configuration-markup/#rendererunsafe
You can suppress this warning by adding the following to your site configuration:
ignoreLogs = ['warning-goldmark-raw-html']
Built in 111 ms
Error: error building site: logged 2 error(s)

**Comment by Fastbyte01** [comment]
should be solved with https://github.com/Fastbyte01/KeepIt/commit/176864f9cd3c101d1a83347ea7e1b0eb009cea39
